language:
- php
- node_js
php:
- 7.1
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer update
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
