language: php
php:
- 7.1
script:
- composer update
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
env:
  global:
  - secure: uGDxPtrsmwwVUS9AKhDaAqSk+Y5hHn7P2lkS7V5dVK93FDFt377j9RlDdXO4f4YfS3NDnsO9B7o1290IbdPQDI6Q9Y9pezBK2fWYVpQPEgw8oezjvxENNAgUs9yQjEzvE0fN0Oy4zefj7P8sf0o/Ozs/QT7cEPzu7Lh7Zs0mAM6Wz4b5EEfSOnkqkmi4fM8aIcAYri5TRGfpU0o66TIj8rYQLr/A/LswFDCDTLpZESusVuoV9xgN/cnS9vpdhyVGDkHQJO402T6TmvoJOxZ3xki9S6WFaVQ5LB2la+X2jhn9/VIL9K4phwRmJ4O+tlt/pzKwzc30vmAO6kxqOwcK/IZ3cZ98MyP/QWVORkZofj0aDmgfrcJ95Pa+1hy8iTHjtJLfqVs20f6S/1U0HbVcK2zHz3X+EXxO5ERpLnNx276caBuXPdOC1lccFNfbqMyCpheHS+yY0IlcF30FbvffkiGXeyeodzP6OFR9h8b3FI3Ds03P8DeCdBVVexssjDbpVgCiCKiekv5s/b7hXBdAttDqYX4YeIsoI18Qdqe59dN0Yz70xPRvGbqsRiALscfKlyJBErWp2N5aPZ6Z5lI0NVqbhZR4EzsFNIGNXZ8qoqFRugz2clCMlMUj4aOQ3m6Zk/I4bVHWBJ1LqvXxUYZQ/MvuV50A2bXDiu5/EGF9L6Y=
  - secure: Sa+KkhQL31dOtS+cVOekPaoTBXPZ6ty7IfNDfcxrCYz8tbg5XdnIpXtWjotjZTCOp8nuh0zCruvSQXxWUc0VGSz1m+x6QVCMNa6qL6/DpUCb6A5dlIyt2n2KiqtJHY4339fpgNoARHUqmjzJKdf0n+Zt7ZFgWqN5DghSdyY+2OL8Apxsn32yDxxgdgOFbAz4+y0EYKFQ4p0ZGdJxT6fRzztH/qs/0ZZbjHY7m5a8qHS8UK4Mh/I1eHBgFqo46iNnkrGm1KvZxhoXj0tOkdVaBt+nSWh8EkFSuGIrqgA4Fz89ukl0FqyA3txS+LBJ728QElBP3MVnNJw6HVLoA/Gb3rNky5qlXojDK4S5sBV5/LaHev14lo42LFSNnHZMCR7VRaYmT+q3aNMw1TvNf9yBk0NwwI0/faf/hn5jXsmG7mOsZ90+FDmXHcQszm2tcSOuGJ4q+tKaIWAr1JNYs+vyXQg0X+T8AjzLhlEMy1cpaqc1Sgwsf3AtMgCMGvB0HQH5+k+wYX6EtsaooSucmYe7xgSTdU74dZ4Rv7PJI0T9LsNf8rUe4Khk0fzOUFjT/N0HMsRybcwMYePBoSb7+s8/B7U6HmdQTTFNW5yuLpCFzJFu/qRW4tWV8QSID51rYaWFa4OoNyRvwdyfkYei+NOfYCzsdmO3k0dRxUgUGdZJtCU=
  - secure: fIljaNWRificeV7SgVfg8UHtXt6il4vOknK5XNKcyX61Z/cFh+Jf6HKvdpshWi5rddfznaoCgOfFMfMZCnjYayO3mee0alD6cTf/cL1L5P0xUp+6IltI2g0WQ1TV74vnspH6KEslcMoedxrZg0jkrqZ8w5CQ9FbSF7YphqUaV6t3tVgQETZt9J54LaqmnFEPhCcbh6dqcbsIlsd1PKVmRiMd2+OS6hvo3gj+6Lf4ceqE7+xfPYBEqlw6v8jmfxPrF0xMpSW3tEfhwvyXNupd+Nb4UF3YPas8EjQjSaULGW4Pn/PdMzqjQjHTBplfcTbz5ijvxW/bD9Etc4onwz7zwlDgPsw2GSYuUARZJ0lXX3ebYfowZt6FGty+ZrMTR55ki5unLhDX3q+kx3Q5NdCn+VjHIUp/ialvjVtksm1PEfullvIKye1devFfHjTcJPruNx5J6wiy99eXblIOAv7iMuBZ3h1w8Rj/AG8AR6fPTnZ54MxuawQI3mxGp4c/wA5GB1rnMKzsvRr7YvCO+hdxzGdRxTjKmCU5CQFw9LXOPPqTWGvpURsbik1s57+IYY2jZfPyQxxpGE6rqwTugGVXuDwrAVgKq1GJlAPGviF/H3HBkxLR/CDeRMX83MtrU6KmwNlDYZPi8y62hoos86g1y2iis0mrmb//+hg1LNevq/c=
